// serpapi.js
//
// WHY THIS FILE EXISTS:
// This utility powers Feature 4 — "Find Me Something Like This."
// After GPT-4o Vision identifies the key fashion item in a user's photo
// and generates search queries, this function calls SerpAPI's Google
// Shopping endpoint to return real products with titles, prices, and links.
//
// IMPORTANT — error handling:
// SerpAPI failures must NEVER crash the app. If the API is down, the key
// is missing, or no results are found, we return an empty array [] and
// let the route handle the empty state gracefully. Feature 4 has an
// explicit "no results" UI state for exactly this reason.
//
// FREE TIER LIMIT:
// SerpAPI's free plan includes 100 searches per month. Test sparingly —
// each test run consumes one search credit.

const axios = require('axios');

// SerpAPI's Google Shopping endpoint — all parameters go in the query string
const SERPAPI_BASE_URL = 'https://serpapi.com/search.json';

// Maximum number of shopping results to return to the caller
const MAX_RESULTS = 8;

// ─────────────────────────────────────────────────────────────────────────────
// searchGoogleShopping
// Searches Google Shopping via SerpAPI for fashion products matching a query.
//
// Parameters:
//   query — a shopping search string generated by GPT-4o Vision,
//           e.g. "olive green tapered cargo trousers relaxed fit"
//
// Returns:
//   Array of up to 8 objects: { title, price, link, thumbnail }
//   Returns [] if no results found or if any error occurs.
//   Never throws — the route must always get a response it can handle.
// ─────────────────────────────────────────────────────────────────────────────
async function searchGoogleShopping(query) {
  try {
    const response = await axios.get(SERPAPI_BASE_URL, {
      params: {
        engine:        'google_shopping',
        q:             query,
        api_key:       process.env.SERPAPI_KEY,
        // Restrict results to India — prices return in ₹, results from Indian retailers
        gl:            'in',
        google_domain: 'google.co.in',
        hl:            'en',
        location:      'India',
      },
      // Timeout after 10 seconds — don't let a slow SerpAPI response
      // hold up the entire feature request
      timeout: 10000,
    });

    const shoppingResults = response.data.shopping_results;

    // SerpAPI returns no shopping_results key at all when nothing is found
    if (!shoppingResults || shoppingResults.length === 0) {
      console.warn('[serpapi] No shopping results found for query:', query);
      return [];
    }

    // Map to the shape the rest of the app expects, and cap at MAX_RESULTS
    return shoppingResults.slice(0, MAX_RESULTS).map((item) => ({
      title:     item.title                     || 'Untitled product',
      price:     item.price                     || 'Price unavailable',
      link:      item.product_link || item.link || '',
      thumbnail: item.thumbnail                 || '',
      // Strip suffixes like " - MNow" or " - Assured" to get the clean retailer name
      source:    item.source ? item.source.split(' - ')[0].trim() : '',
    }));

  } catch (error) {
    // Log the error for debugging in Railway logs but never re-throw —
    // an empty result is always safer than a crashed request
    console.error('[serpapi] searchGoogleShopping failed:', error.message);
    return [];
  }
}

module.exports = { searchGoogleShopping };