// supabase.js
//
// WHY THIS FILE EXISTS:
// All database reads and writes in StyleSense go through these four functions.
// Keeping Supabase logic here means route files stay focused on request/response
// handling and never contain raw database queries. If the schema changes,
// there is exactly one file to update.
//
// IMPORTANT — embeddings:
// The `embedding` column in wardrobe_items is type VECTOR(1536).
// Supabase's JS client accepts a plain JavaScript array for this column.
// Never convert the embedding to a string before passing it here —
// it will cause an insert failure.

const { createClient } = require('@supabase/supabase-js');

// Initialise the Supabase client once using credentials from environment variables.
// SUPABASE_URL      — looks like https://xxxx.supabase.co
// SUPABASE_ANON_KEY — the long eyJ... token from your Supabase project settings
const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_ANON_KEY
);

// ─────────────────────────────────────────────────────────────────────────────
// saveProfile
// Upserts a user style profile into the user_profile table.
// "Upsert" means: insert if this session_id doesn't exist yet,
// or update the existing row if it does. This way re-running onboarding
// overwrites the old profile rather than creating a duplicate.
//
// Parameters:
//   sessionId   — the localStorage UUID that identifies this user's session
//   profileJson — the parsed profile object generated by GPT-4o
//
// Returns:
//   { success: true } on success
//   { success: false, error: string } on failure
// ─────────────────────────────────────────────────────────────────────────────
async function saveProfile(sessionId, profileJson) {
  try {
    const { error } = await supabase
      .from('user_profile')
      .upsert(
        { session_id: sessionId, profile_json: profileJson },
        { onConflict: 'session_id' }
      );

    if (error) {
      console.error('[supabase] saveProfile error:', error.message);
      return { success: false, error: error.message };
    }

    return { success: true };
  } catch (err) {
    console.error('[supabase] saveProfile unexpected error:', err.message);
    return { success: false, error: err.message };
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// getProfile
// Retrieves the style profile for a given session.
//
// Parameters:
//   sessionId — the localStorage UUID
//
// Returns:
//   The profile_json object if found, or null if no profile exists yet.
//   Routes should handle the null case gracefully (e.g. proceed without profile).
// ─────────────────────────────────────────────────────────────────────────────
async function getProfile(sessionId) {
  try {
    const { data, error } = await supabase
      .from('user_profile')
      .select('profile_json')
      .eq('session_id', sessionId)
      .single();

    if (error) {
      // PGRST116 means no rows found — that is expected for new users, not an error
      if (error.code === 'PGRST116') return null;
      console.error('[supabase] getProfile error:', error.message);
      return null;
    }

    return data.profile_json;
  } catch (err) {
    console.error('[supabase] getProfile unexpected error:', err.message);
    return null;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// saveWardrobeItem
// Inserts one wardrobe item into the wardrobe_items table.
// Called after a garment image has been uploaded to Cloudinary and tagged
// by GPT-4o Vision. The embedding is stored as a VECTOR(1536) column
// which powers semantic search in findTopK().
//
// Parameters:
//   sessionId  — the localStorage UUID
//   imageUrl   — the Cloudinary secure_url for this garment
//   tags       — the parsed tag object from GPT-4o (type, colour, fit, etc.)
//   embedText  — the plain text string that was embedded (for reference)
//   embedding  — plain JS array of 1536 floats — do NOT convert to string
//
// Returns:
//   The full created row object (including its auto-generated UUID)
// ─────────────────────────────────────────────────────────────────────────────
async function saveWardrobeItem(sessionId, imageUrl, tags, embedText, embedding) {
  try {
    const { data, error } = await supabase
      .from('wardrobe_items')
      .insert({
        session_id: sessionId,
        image_url:  imageUrl,
        tags:       tags,
        embed_text: embedText,
        embedding:  embedding,   // plain JS array — Supabase handles VECTOR casting
      })
      .select()
      .single();

    if (error) {
      console.error('[supabase] saveWardrobeItem error:', error.message);
      throw new Error('Failed to save wardrobe item. Please try again.');
    }

    return data;
  } catch (err) {
    console.error('[supabase] saveWardrobeItem unexpected error:', err.message);
    throw new Error('Failed to save wardrobe item. Please try again.');
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// getWardrobeItems
// Retrieves all wardrobe items for a given session.
// Called by feature routes before running semantic search with findTopK().
//
// Parameters:
//   sessionId — the localStorage UUID
//
// Returns:
//   Array of wardrobe item objects (may be empty [] if none uploaded yet).
//   Each item includes: id, image_url, tags, embed_text, embedding.
// ─────────────────────────────────────────────────────────────────────────────
async function getWardrobeItems(sessionId) {
  try {
    const { data, error } = await supabase
      .from('wardrobe_items')
      .select('id, image_url, tags, embed_text, embedding')
      .eq('session_id', sessionId);

    if (error) {
      console.error('[supabase] getWardrobeItems error:', error.message);
      return [];
    }

    return data || [];
  } catch (err) {
    console.error('[supabase] getWardrobeItems unexpected error:', err.message);
    return [];
  }
}

module.exports = { saveProfile, getProfile, saveWardrobeItem, getWardrobeItems };